name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [":", ":app", ":simple-starter", ":spring-app", ":spring-app-currency"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build and run tests
        run: ./gradlew ${{ matrix.module }}clean ${{ matrix.module }}build ${{ matrix.module }}test

      - name: Generate test coverage report
        if: matrix.module == ':'
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        if: matrix.module == ':'
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Upload Checkstyle report
        uses: actions/upload-artifact@v3
        if: matrix.module == ':'
        with:
          name: checkstyle-report
          path: build/reports/checkstyle

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    strategy:
      matrix:
        module: [spring-app, spring-app-currency]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}-${{ matrix.module }}:latest ./${{ matrix.module }}
          docker push ghcr.io/${{ github.repository }}-${{ matrix.module }}:latest